### ISSUE TITLE
Glob patterns

### ISSUE THREAD

**Issue by The-Noah** [The-Noah/lsfp#19]
**Is your feature request related to a problem? Please describe.**
You can't use things like `ls projects/*/src`

**Describe the solution you'd like**
Simple glob patterns, even just `*`

**Comment by HipyCas** [comment]
Playing around with lsfp and glob patterns I have discovered something quiet funny. With commit e55a2efdb30ea7b4b742679c7227b296814e3442, which canonicalized (made absolute) the path passed, support for basic single file glob patterns was introduced. It turns out `canonicalize()` also resolves glob patterns, but only returns the first result. With this (on lsfp's git directory), running `lsfp *.md` prints **ONLY** _README.md_, running `lsfp *.rs` prints _build.rs_ (as expected only returns one result), and even running `lsfp src/m*/f*s` works printing `file_size.rs`.

**Comment by The-Noah** [comment]
Ohhh nice!! This is quite interesting.

**Comment by HipyCas** [comment]
To keep lsfp dependency-less, I have thought of using C code to implement this, as I cannot find any native way of implementing that in rust. Is there any problem with implementing the code in C?

**Comment by The-Noah** [comment]
I'd highly prefer everything being written in Rust, but if you write it in C that's fine.

You can see this commit where I added some C code: dbbe3e04bc0c47f198bbdee53b5f5ddfb1e0df38

**Comment by HipyCas** [comment]
The C code turned out not to be needed, take a look at #55, everything was simpler than I though.
